// Build script: enumerate corpus/sqlite_parity/cases/*.json so each shard
// can be reached via include_str!. The runner needs a literal-path include,
// and we want to discover shards at compile time without committing a Rust
// "shard registry" by hand.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let cases_dir = manifest_dir
        .join("corpus")
        .join("sqlite_parity")
        .join("cases");

    // Always rerun if the directory listing changes, even when empty.
    println!("cargo:rerun-if-changed={}", cases_dir.display());

    let mut shards: Vec<PathBuf> = Vec::new();
    if cases_dir.is_dir() {
        for entry in fs::read_dir(&cases_dir).expect("read sqlite_parity/cases dir") {
            let entry = entry.expect("read sqlite_parity/cases entry");
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "json") {
                println!("cargo:rerun-if-changed={}", path.display());
                shards.push(path);
            }
        }
    }
    shards.sort();

    let mut emit = String::new();
    emit.push_str("// AUTO-GENERATED by build.rs. Do not edit by hand.\n");
    emit.push_str("// Each entry is (file_stem, include_str!(absolute_path)).\n");
    emit.push_str("pub static EXTENDED_SHARDS: &[(&str, &str)] = &[\n");
    for path in &shards {
        let stem = path.file_stem().expect("shard stem").to_string_lossy();
        let abs = canonical(path);
        // Use raw-string literal so backslashes (if any) on non-unix paths
        // pass through unchanged.
        emit.push_str(&format!(
            "    (\"{stem}\", include_str!(r\"{}\")),\n",
            abs.display()
        ));
    }
    emit.push_str("];\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("extended_shards.rs");
    fs::write(&out_path, emit).expect("write extended_shards.rs");
}

fn canonical(path: &Path) -> PathBuf {
    fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())
}
