use anyhow::{Context, Result, bail};

use super::case::Case;

const PINNED_MANIFEST: &str = include_str!("../../corpus/sqlite_parity/generated_manifest.json");

// EXTENDED_SHARDS is generated by build.rs from corpus/sqlite_parity/cases/*.json.
// Each entry is (file_stem, shard_contents_as_str).
include!(concat!(env!("OUT_DIR"), "/extended_shards.rs"));

/// Cases from the pinned upstream manifest (IDs 1-1127). Read-only; this is
/// the migrated artifact from RedlineDB.
pub fn pinned_cases() -> Result<Vec<Case>> {
    serde_json::from_str(PINNED_MANIFEST)
        .context("parse sqlite parity pinned generated_manifest.json")
}

/// Cases authored directly in this repo (ID >= 10001). Loaded shard by shard
/// in alphabetical order so report enumeration is deterministic.
pub fn extended_cases() -> Result<Vec<Case>> {
    let mut all = Vec::new();
    for (stem, body) in EXTENDED_SHARDS {
        // Skip pure metadata shards (those starting with an underscore are
        // not case lists — see corpus/sqlite_parity/cases/_capabilities.json
        // for the data-driven capability table).
        if stem.starts_with('_') {
            continue;
        }
        let cases: Vec<Case> = serde_json::from_str(body)
            .with_context(|| format!("parse sqlite_parity/cases/{stem}.json"))?;
        all.extend(cases);
    }
    Ok(all)
}

/// Pinned + extended cases in canonical order (pinned first, then extended
/// by shard filename).
pub fn all_cases() -> Result<Vec<Case>> {
    let mut all = pinned_cases()?;
    all.extend(extended_cases()?);
    Ok(all)
}

pub fn selected_official_cases() -> Result<Vec<Case>> {
    let pinned_only = matches!(
        std::env::var("REDLINE_TESTING_PINNED_ONLY").ok().as_deref(),
        Some("1") | Some("true") | Some("TRUE")
    );
    let cases = if pinned_only {
        pinned_cases()?
    } else {
        all_cases()?
    };
    let cases = cases
        .into_iter()
        .filter(|case| case.status == "active" || case.status == "catalog_only")
        .collect::<Vec<_>>();
    if cases.is_empty() {
        bail!("sqlite parity selection matched zero cases");
    }
    Ok(cases)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sqlite_parity::case::Priority;

    #[test]
    fn pinned_manifest_has_planned_size_and_ranges() {
        let cases = pinned_cases().expect("sqlite parity pinned manifest");
        assert_eq!(cases.len(), 1127);
        assert_eq!(cases[0].display_id(), "00001");
        assert_eq!(cases[1126].display_id(), "01127");
        assert_eq!(
            cases
                .iter()
                .filter(|case| case.priority == Priority::P0)
                .count(),
            130
        );
        assert_eq!(
            cases
                .iter()
                .filter(|case| case.priority == Priority::P1)
                .count(),
            579
        );
        assert_eq!(
            cases
                .iter()
                .filter(|case| case.priority == Priority::P2)
                .count(),
            370
        );
        assert_eq!(
            cases
                .iter()
                .filter(|case| case.priority == Priority::P3)
                .count(),
            24
        );
    }

    #[test]
    fn extended_ids_start_above_upstream_reserve() {
        // The pinned upstream range is 1..=1127, with 1128..=9999 reserved
        // for upstream growth. New cases authored in this repo land at >= 10001.
        let extended = extended_cases().expect("extended shards");
        for case in &extended {
            assert!(
                case.id >= 10001,
                "extended case id={} must be >= 10001 (reserve 1128..=9999 for upstream)",
                case.id
            );
        }
    }

    #[test]
    fn combined_official_selection_is_ordered() {
        let cases = selected_official_cases().expect("official cases");
        assert!(!cases.is_empty());
        // Pinned cases come first, then extended; ids are strictly increasing.
        assert!(cases.windows(2).all(|pair| pair[0].id < pair[1].id));
        // P4 is present in the pinned set; it must survive selection.
        assert!(cases.iter().any(|case| case.priority == Priority::P4));
    }
}
